version = 2

[extensions]
mal_cord = "https://github.com/Goldy-Bot/mal_cord"
aghpb_cord = "https://github.com/Goldy-Bot/aghpb_cord"
fun_plus_plus = "https://github.com/Goldy-Bot/fun_plus_plus"
timestamps = "https://github.com/Goldy-Bot/timestamps"
osu = "https://github.com/Goldy-Bot/osu"
